### ISSUE TITLE
Diseñar la base de datos del proyecto

### ISSUE THREAD

**Issue by jordandd56** [djsegovia1/Todopublico#2]
Crear el modelo de datos para la base de datos del proyecto, incluyendo las tablas USUARIOS, ACTIVIDADES, y sus relaciones. Utilizar PostgreSQL para la implementación.

**Comment by kgmarcillo** [comment]
No vite? ta hecho

**Comment by capumadev** [comment]
No mi compa no me llega la trasferencia
